name: Workflow Matrix
on:
  workflow_dispatch: 
jobs:
  exemplo-fluxo-execucao:
    strategy:
      matrix:
        versao: [16,18,20]
        plataforma: ["windows","ubuntu"]
    runs-on: "${{ matrix.plataforma }}-latest"
    steps:
      - name: Instalação do node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.versao }}
      - name: Exibição da versão e da plataforma
        run: |
            node --version
            echo ${{ runner.os }}