name: Workflow Eventos
on:
  push:
jobs:
  apenas-main:
    if: ${{ github.ref  == 'refs/heads/main'}}
    name: Esse Job só executa na branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executando na main
        run: echo "Executando comando na main"
  todos:
    runs-on: ubuntu-latest
    steps:
      - name: Execução em Feature
        run: echo "Execução em Feature"
      - name: Execução em Hotfix
        run: echo "Execução em hotfix"