name: Workflow Eventos
on:
  workflow_dispatch: 
    inputs:
      valor_numerico: 
        type: number
        default: 20
      valor_string: 
        type: string
        default: "Valor XPTO"
      valor_boolean:
        type: boolean
        default: true
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Operação com string
        run: echo "${{ github.actor == inputs.valor_string }}"
      - name: Operação com number
        run: echo "${{ inputs.valor_numerico > 20 }}"
      - name: Operação boolean
        run: echo "${{ !inputs.valor_boolean }}"