name: Workflow Eventos
on:
  pull_request: 
    branches: ["main"]
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: echo "Action executada apenas em main e features"
      - name: Alteração no card
        uses: actions/github-script@v6
        with: 
          script: |
            github.rest.issues.createCommit({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Adicionando um comentário aqui sobre o PR'
            })