name: Workflow Eventos
on:
  push:
    # branches: ["main", "feature/*"]
    tags:
      - v*
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de Teste
        run: echo "Action executada apenas em main e features"
