name: Workflow concorrencia
run-name: Workflow Concorrencia ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      chave:
        type: string
        default: pipeline-aula
concurrency: ${{ inputs.chave }}
jobs:
  exemplo-fluxo-execucao-01:
    runs-on: ubuntu-latest
    steps:
      - name: Execução do job teste
        run: |
          sleep 120;
          echo "Action executada job 01"
  